### ISSUE TITLE
Updating the mappy build system [Help wanted!]

### ISSUE THREAD

**Issue by lh3** [lh3/minimap2#1053]
Minimap2 currently uses setup.py for build and distributing the mappy Python module. However, with the old system being deprecated, I am unable to update the module at PyPI now. Could someone help? Thanks.

In the past, I was running
```sh
python setup.py sdist upload -r pypi
```
Now on my M1 Mac, I got the following errors (only showing the end of the log):
```txt
copying python/mappy.pyx -> mappy-2.25/python
copying python/minimap2.py -> mappy-2.25/python
copying sse2neon/emmintrin.h -> mappy-2.25/sse2neon
Writing mappy-2.25/setup.cfg
creating dist
Creating tar archive
removing 'mappy-2.25' (and everything under it)
running upload
Traceback (most recent call last):
  File "/Users/hli/Dropbox/dev/github/minimap2/setup.py", line 35, in <module>
    setup(
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/command/upload.py", line 72, in run
    self.upload_file(command, pyversion, filename)
  File "/Users/hli/conda/lib/python3.10/site-packages/setuptools/_distutils/command/upload.py", line 81, in upload_file
    raise AssertionError("unsupported schema " + schema)
AssertionError: unsupported schema
```
PS: I can build and use the mappy module but I am unable to upload the package to PyPI.

**Comment by lh3** [comment]
It seems that I can use twine to upload. Close it for now.
