### ISSUE TITLE
paftools stat: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tseemann** [lh3/minimap2#153]
I assume `paftools stat` needs a CIGAR string via `--cs` option etc.

Perhaps exit after first missing CIGAR and give a friendly error to this effect?

```
WARNING: no CIGAR at line 1
<snip>
/home/linuxbrew/.linuxbrew/bin/paftools.js:578: TypeError: Cannot read property '0' of undefined
                var st = regs[0][0], en = regs[0][1], l = 0;
                  ^
TypeError: Cannot read property '0' of undefined
    at cov_len (/home/linuxbrew/.linuxbrew/bin/paftools.js:578:19)
    at paf_stat (/home/linuxbrew/.linuxbrew/bin/paftools.js:679:11)
    at main (/home/linuxbrew/.linuxbrew/bin/paftools.js:2020:26)
    at /home/linuxbrew/.linuxbrew/bin/paftools.js:2033:1
```

**Comment by lh3** [comment]
Fixed via 39f836e. Thanks.
