### ISSUE TITLE
paftools lift-over - CIGAR is inconsistent with mapping coordinates

### ISSUE THREAD

**Issue by fbemm** [lh3/minimap2#279]
Hi,

I have the following PAF file:

Seq1  169     0       159     -       chr1    57626310        21118450        21118607        154     156     60      NM:i:5  ms:i:289        AS:i:289        nn:i:3  tp:A:P  cm:i:9  s1:i:84 s2:i:0  cg:Z:14=1X43=1X23=2I10=1X64=    MD:Z:14T43C33T64`

and a BED file:

`Seq1  100     101`

I would like to lift-over a single coordinate in a relatively small alignment and paftools stops with the folliowing error:

```
paftools.js:320: Error: CIGAR is inconsistent with mapping coordinates
                        throw Error("CIGAR is inconsistent with mapping coordinates");
         ^
Error: CIGAR is inconsistent with mapping coordinates
    at Error (<anonymous>)
    at paf_liftover (paftools.js:320:10)
    at main (paftools.js:2368:51)
    at paftools.js:2380:1
```

I guess the problem is the t[2] in `y != t[1] - t[2]'. Looks like it is 0:

`s1e0029xxx@101,169,0,159,-,chr1,57626310,21118450,21118607,154,156,60,NM:i:5,ms:i:289,AS:i:289,nn:i:3,tp:A:P,cm:i:9,s1:i:84,s2:i:0,cg:Z:14=1X43=1X23=2I10=1X64=,MD:Z:14T43C33T64`

Any idea why this is happening?

**Comment by yeeus** [comment]
Do you plan to add the `--eqx` consistant feature to `paftools.js liftover`?
