### ISSUE TITLE
paftools.js to convert STAR sam files?

### ISSUE THREAD

**Issue by christopher-vollmers** [lh3/minimap2#805]
Hi,

I apologize if this is an "off label" use case. I am trying to convert a STAR sam to a paf file using paftools.js
I am doing this to generate a long cs string so I can determine position dependent sequencing error.
At this line in the sam file, paftools.js generates the following error:

`SRR4235534.1    147     chr20   5118616 255     62M91N14M       =       5117563 -1220   TCCAAATTGTTCAACATCTAAATCCATCAACTTCATTTCATAGTCTGAAACTTTCTCCTGGTTTTGTGCTTCAAAT    1?4-?39/09=@@@@@/>>>>(4;;?(76;;(9>6<97;;;46?>.4<4?.>8>7.>:>>92-4))8>/::@@*@9    NH:i:1  HI:i:1  NM:i:2  MD:Z:5G58G11    AS:i:142        nM:i:4  jM:B:c,22       jI:B:i,5118678,5118768  XS:A:-`

`/home/ig88/Downloads/minimap2/misc/paftools.js:1751: Error: at line 314: inconsistent MD tag
						} else throw Error("at line " + lineno + ": inconsistent MD tag");
                   ^
Error: at line 314: inconsistent MD tag
    at Error (<anonymous>)
    at paf_sam2paf (/home/ig88/Downloads/minimap2/misc/paftools.js:1751:20)
    at main (/home/ig88/Downloads/minimap2/misc/paftools.js:2613:29)
    at /home/ig88/Downloads/minimap2/misc/paftools.js:2634:1`

Is there enough variation between how different tools are generating CIGAR and MD strings to make this type of universal conversion impossible?

Thank you for your help.

Best,
Chris

**Comment by lh3** [comment]
paftools.js doesn't support the splicing operator (aka `N`).

**Comment by christopher-vollmers** [comment]
Ah okay. Makes sense. Looks like I'll have to parse CIGAR and MD strings myself. Not looking forward to that. Thank you for your help. BTW, the long cs string is a fantastic addition to minimap2. Super helpful.

Best,
Chris

**Comment by lh3** [comment]
paftools works with STAR sam output now.
