### ISSUE TITLE
mappy how to use extra_flags end_bonus

### ISSUE THREAD

**Issue by DelphIONe** [lh3/minimap2#980]
Hi lh3,

I tried to use tombo after resquiggle.py modified but I have one problem :
tombo resquiggle --rna --processes 4 --corrected-group RawGenomeCorrected_000 --overwrite ../../fast5_gzip_single/ ../../ref/single.fasta
[11:38:39] Loading minimap2 reference.
Traceback (most recent call last):
  File "/usr/local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo', 'console_scripts', 'tombo')()
  File "/home/xxx/softs/tombo/tombo/__main__.py", line 231, in main
    resquiggle._resquiggle_main(args)
  File "/home/xxx/softs/tombo/tombo/resquiggle.py", line 2033, in _resquiggle_main
    aligner = mappy.Aligner(str(args.reference), preset=str('sr'), k=6, best_n=1, extra_flags=str('end_bonus 200'))
  File "python/mappy.pyx", line 130, in mappy.Aligner.__cinit__
TypeError: unsupported operand type(s) for |=: 'int' and 'str'

Can you indicated me which is the good syntax to do this please ?
Thanks a lot,

**Comment by DelphIONe** [comment]
anyone please ?

**Comment by lh3** [comment]
Mappy doesn't support `end_bonus`.

**Comment by DelphIONe** [comment]
Are you sure ? In minimap.h (https://github.com/lh3/minimap2/blob/master/minimap.h) there is 
int end_bonus line 157 :-(

**Comment by lh3** [comment]
Yes, I am sure. Mappy doesn't support end_bonus.

**Comment by DelphIONe** [comment]
Maybe can you help me on #256 
Sorry to insist...

**Comment by lh3** [comment]
I don't have a good solution about #256.
