### ISSUE TITLE
paftools 'inconsistent thick start or end' error

### ISSUE THREAD

**Issue by chilampoon** [lh3/minimap2#988]
Hey there,

I was running paftools on T2T gff3 to get the bed file but ran into an error:
```
paftools.js gff2bed chm13.draft_v2.0.gene_annotation.gff3 > chm13.draft_v2.0.gene_annotation.bed
/gpfs/commons/home/cpoon/miniconda3/envs/ont/bin/paftools.js:1598: Error: inconsistent thick start or end for transcript CHM13_T0000080
                        throw Error("inconsistent thick start or end for transcript " + a[0][4]);
         ^
Error: inconsistent thick start or end for transcript CHM13_T0000080
    at Error (<anonymous>)
    at print_bed12 (/gpfs/commons/home/cpoon/miniconda3/envs/ont/bin/paftools.js:1598:10)
    at paf_gff2bed (/gpfs/commons/home/cpoon/miniconda3/envs/ont/bin/paftools.js:1666:4)
    at main (/gpfs/commons/home/cpoon/miniconda3/envs/ont/bin/paftools.js:3126:29)
    at /gpfs/commons/home/cpoon/miniconda3/envs/ont/bin/paftools.js:3148:1
```

That gff3 was download from [here](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13.draft_v2.0.gene_annotation.gff3). Could you help fix it? Thanks!

**Comment by lh3** [comment]
try [gffio](https://github.com/lh3/gffio) gff2bed
